import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import ModeSelector from "../components/ModeSelector/ModeSelector";
import "@fontsource/vt323"
import TextBox from "../components/TextBox/TextBox";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.left}>
      <ModeSelector />
      </div>
      <main className={styles.main}>
        <h1>Your decisions your story</h1>
        <TextBox/>
      </main>
    </>
  );
}
